### ISSUE TITLE
Link error

### ISSUE THREAD

**Issue by Mohammadtej** [vaidarbhicontractor/Roadmap_to_learn_Android_App_Development#1]
Hello the first javapoint link doesn't work, can you please replace it? Thanks for the roadmap

**Comment by vaidarbhi01** [comment]
Hello Mohammadtej , Many thanks for visit my repository and draw my attention at non working link. I updated it recently so please go with it. Thank you so much once again and happy learning :)

**Comment by vaidarbhicontractor** [comment]
Hello Mohammadtej , Many thanks for visit my repository and draw my
attention at non working link. I updated it recently so please go with it.
Thank you so much once again and happy learning :)

**Comment by Mohammadtej** [comment]
Yeah, I just want to say a huge thanks to developers like you who would guide us newbies and help them with the resources. Keep doing the good work:)
